<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
  <title>AustNet.org :: Routing Policies</title>
  <script type="text/javascript"></script>
  <style type="text/css" title="currentStyle" media="screen">
    @import "austnet.css";
  </style>
</head>
<body id="austnet">
  <div id="container">
    <div id="header">
    </div>
    <div id="content">
      <div class="wrapper">
      <ul id="tabnav">
        <li><a href="routing.php">Team</a></li>
        <li class="current"><a href="#">Policies</a></li>
        <li><a href="http://www.austnet.org/serverapp.txt">Applications</a></li>
        <li><a href="routing_contacts.php">Contacts</a></li>
      </ul>
      <p><strong>Routing Policies</strong></p>
      <p>In this document:</p>
      <ul>
        <li>The word &#39;<strong>IRCD</strong>&#39; and the phrase &#39;<strong>IRC DAEMON</strong>&#39; denote the IRC Server software to be run on the server machine. </li>
        <li>The word &#39;<strong>SERVER</strong>&#39; denotes the computer indicated by application to run the IRC Daemon. </li>
        <li>The word &#39;<strong>APPLICANT</strong>&#39; denotes the person applying; The administrator of the server. </li>
        <li>The words &#39;<strong>MUST</strong>&#39; and &#39;<strong>WILL</strong>&#39; denote a requirement that is absolutely mandatory. </li>
        <li>The phrases &#39;<strong>MUST NOT</strong>&#39; and &#39;<strong>WILL NOT</strong>&#39; denote a requirement that is absolutely prohibited. </li>
        <li>The words &#39;<strong>SHOULD</strong>&#39; and &#39;<strong>RECOMMENDED</strong>&#39; denote a specification that would assist the application. </li>
        <li>The phrases &#39;<strong>SHOULD NOT</strong>&#39; and &#39;<strong>NOT RECOMMENDED</strong>&#39; denote a specification that would not assist the application. </li>
      </ul>
      <p><strong>Criteria <em>required</em> for application: </strong></p>
      <ol>
        <li>The server running the IRC Daemon software <em>must</em> be able to run constantly; 24 hours a day, 7 days a week. </li>
        <li>The server <em>must</em> be available for at least the next 2 (two) years. If the applicant is aware that the server may not remain on-line this long, please do not apply. Applications <em>must</em> be for the long-term, and <em>must not</em> be temporary. </li>
        <li>The server <em>must</em> have at least:
          <ul>
            <li>A Family-5 or better processor (on Intel x86/IA32 machines) running at 400MHz or higher. </li>
            <li>An Ultra-10 or better for Sun Sparc based machines. </li>
            <li>Must be configured to allow a minimum of 2048 file descriptors open per process. </li>
            <li>128 Megabytes of RAM minimum (or as appropriate to the operating system and the maximum number of file descriptors given above). </li>
            <li>Other platforms should run a comparable, or better system. </li>
          </ul>
        </li>
        <li>The server <em>must</em> have UNIX or a variant as its operating system (FreeBSD, NetBSD, OpenBSD, Linux, Solaris, Digital Unix, BSDi, et cetera). Our IRCD <em>will not</em> run on NT. Alpha, Beta, Development or Pre-Release or similarly specified versions of the operating system <em>must not</em> be used. </li>
        <li>The server specifications <em>must</em> be finalised prior to application. Changing specifications or applying with notes about future planned upgrades are not helpful. </li>
        <li>The applicant <em>must</em> have &#39;root&#39; access to the server, or an appropriate level of administrative access to change set up parameters of the server. </li>
        <li>If the server and/or its connection(s) to the Internet are deemed by AustNet unable or unsuitable to cope with the load generated by IRC traffic, the application <em>will</em> be rejected. </li>
        <li>The server <em>must</em> be connected to an internal network by way of a switching repeater (&#39;Network Switch&#39;), or a secured repeater (a repeater which removes packet contents for nodes not authorised to receive the data). </li>
        <li>The server <em>must</em> be protected by a suitable firewall to protect it against malicious attacks. However, the firewall <em>must not</em> impede ICMP type 3 code 4 (Fragmentation needed and DF flag set) packets. </li>
        <li>The server <em>must</em> be running all current security patches. The applicant <em>must</em> be able to update any software or hardware as required in the future, or be able to make appropriate arrangements for such updates quickly. </li>
        <li>The applicant <em>must</em> be fully aware and have read the AustNet Charter, as well as any other rules and regulations that may be ammended from time to time. </li>
        <li>The applicant <em>must</em> hold harmless all those involved in the network, including but not limited to AustNet server administrators, AustNet hub administrators, AustNet server application administrators, AustNet Services Department (ASD) staff, AustNet Development Staff and users. </li>
        <li>Applicants, Sponsors, Operators (and any other person/organisation associated with the server) <em>must</em> conform and act within the bounds of local and international laws. </li>
        <li>The server <em>must</em> be sponsored from a reliable Internet Service Provider (ISP) or an Application Service Provider (ASP). Co-located (hosted) servers or dedicated servers will only be accepted when:
          <ol>
            <li>The service has been pre-paid at least 2 years (Proof must be given of this). </li>
            <li>The server serves a distinctly defined need to the AustNet network, beyond providing another server in the area or region. </li>
            <li>There are only one or two other server operators besides the admin listed </li>
            <li>The zone representative makes the determination that the server and its staff are reputable and are not applying simply to become IRC Operators (eg. to achieve a high level of status on the network). </li>
          </ol>
        </li>
        <li>Server applications are only considered if they could be of an advantage to the AustNet network. Average servers or servers that are not better than existing ones in the same geographic location are not an advantage. </li>
        <li>Applicants, sponsors, server operators and/or associates who have a reputation from AustNet or other IRC networks in regards to causing trouble, abusing privileges, abusing access, abusing users, not forfilling their duties or any negative reputation to the same or similar effect <em>will</em> result in the server being rejected. If the reputation is of that of an operator, and not the server applicant, the applicant will be given the opportunity to remove the operator in question. </li>
        <li>The applicant <em>must</em> have explicit permission from the server owner and network management (not just the owner of the account on which the IRC Daemon is intended to run) prior to application. Objections from the machine owner <em>will</em> automatically result in rejection. </li>
        <li>The server <em>must</em> have Network Operations Center (NOC) and/or net-block approval, and/or any other approval appropriate to the applying server&#39;s location <strong>prior</strong> to application. This <em>will</em> be checked by your zone representative. </li>
        <li>The server <em>must not</em> be running any services, processes or daemons which are considered high-traffic, high-load or a security risk, including but not limited to:
          <ul>
            <li>Diagnostics and host information services, including &#39;echo&#39;, &#39;discard&#39;, &#39;chargen&#39;, &#39;systat&#39;, &#39;netstat&#39;, &#39;rstat&#39;, &#39;finger&#39;, &#39;nicname&#39; or similar services. </li>
            <li>Remote access services including &#39;telnet&#39;, &#39;rtelnet&#39;, &#39;login&#39; (rlogin), &#39;rje&#39;, &#39;rsh&#39;, &#39;xdmcp&#39; or similar services. Note that &#39;ssh&#39; is acceptable as long as it is reasonably firewalled and not SSH protocol version 1 (one) which has security issues. </li>
            <li>Data/Information access services including &#39;ftp&#39;, &#39;tftp&#39;, &#39;MOX&#39;, &#39;gopher&#39;, &#39;smtp&#39;, &#39;pop&#39; (any version) or similar services. Note that &#39;http&#39; is acceptable as long as it is only used to redirect clients to another server, and not used for serving files itself, or acting as a proxy. </li>
            <li>IRC &#39;bots&#39; including &#39;eggdrop&#39; and similar. </li>
            <li>Redirection services including proxies (&#39;http&#39;, &#39;socks&#39;, &#39;ftp&#39; etc), IRC BNCs and similar services. </li>
            <li>Database based services such as sql servers (&#39;mysql&#39;), &#39;ldap&#39;, and similar. </li>
            <li>Game servers such as &#39;quakeworld&#39;, any mud (&#39;moo&#39;, &#39;mush&#39;, &#39;mux&#39; et cetera), &#39;egs&#39; and similar services. </li>
          </ul>
          Open ports <em>will</em> be checked by your zone representative. </li>
        <li>The server <em>must not</em> act as a gateway, or any other redirection service. </li>
        <li>The server <em>must</em> have its timezone set up to the timezone appropriate to the geographical location of the server. </li>
        <li>During the application process, the server <em>must not</em> have any IRC daemons connected to any IRC networks. </li>
        <li>The server <em>must not</em> run as a &#39;virtual host&#39;, such as running on a non-primary or non-default IP bound to the same ethernet address on the same machine. To do so would be not running a dedicated server. </li>
        <li>Applications <em>must not</em> be from public shell/mud/ircd hosting services (or similar hosts) including but not limited to services such as &#39;CyberPassport&#39;, &#39;Foonet&#39;, &#39;GhostWeb&#39;, &#39;Grid9&#39;, &#39;InterServ&#39;, &#39;IRCWeb&#39;, &#39;Lomag&#39;, &#39;Megalinks&#39;, &#39;PHIX-Net&#39; or &#39;ShellServer&#39;. This is to ensure that we do not lose servers if someone forgets to pay their bill, or that the machine is not a source of various malicious behaviour. This is also to ensure the server&#39;s security. </li>
        <li>Applicants <em>must not</em> provide a contact e-mail address from any form of free e-mail account including but is not limited to e-mail services provided by &#39;hotmail&#39;, &#39;yahoo&#39;, &#39;altavista&#39; or similar services provided with free services such as &#39;sourceforge&#39;, or free shell services. </li>
      </ol>
      <p><strong>Criteria <em>recommended</em> for application:</strong> </p>
      <ol>
        <li>The following are bandwidth recommendations are made:
          <ul>
            <li>If you are applying from within Australia your connection to the Internet <em>should</em> be at least a 8Mbps (DS2-EUR or similar) multihomed connection. </li>
            <li>If you are applying from the US or Canada your connection to the Internet <em>should</em> be at least a 45Mbps (T3/DS3 or similar) connection, preferably also multihomed. </li>
            <li>If you are applying elsewhere your connection to the Internet <em>should</em> be at least a 2Mbps (E1 or similar) or 3Mbps (DS1c or similar) connection. </li>
            <li>Aggregated connections amounting to the same bandwidth are <em>not recommended</em>. </li>
          </ul>
        </li>
        <li>It is <em>recommended</em> that the server run a DNS caching daemon, such as the latest version of BIND (set up in cache-only mode) or a similar appropriate daemon, which <em>must</em> be configured <strong>only</strong> to run on the local interface (localhost). </li>
        <li>It is <em>recommended</em> that the server be set up to synchronise its system clock using an appropriate method such as &#39;xntpd&#39;, or &#39;netdate&#39; in a cron job to maintain an accurate clock as appropriate. If set up as such, the synchronisation source <em>should</em> be reliable, for example a stratum-2 time source. </li>
        <li>It is <em>recommended</em> that applications contain the least number of operators (O-lines) possible. AustNet takes into account each operator that appears on your application in great detail. </li>
      </ol>
      <p><strong> Conditions for guaranteed rejection: </strong></p>
      <ol>
        <li>Fields not filled in correctly and precisely in the application form; <br />
          We require all information to be filled out. Some fields may not appear important to you, but they are to us. </li>
        <li>Lying about <strong>any</strong> information; <br />
          The administrators thorougly check applying servers before considering them, and they may request access to the server for confirmation. </li>
        <li>Mass-applying (for example, applying for a link to other networks at the same time); <br />
          This usually results in immediate rejection as it wastes our time, and shows you are desparate. </li>
        <li>Applying while connected to any other network(s); <br />
          Not only is this disloyal to the other network(s), but gives us the impression that you &quot;network hop&quot; or are desperate for a link. </li>
        <li>Failure to meet any of the <strong>requirements</strong> above; <br />
          This wastes our time, and future applications may be ignored. </li>
        <li>Too many Operators (O-lines) listed; <br />
          This shows us that either you or your operators are not willing to spend much time administering the server, or you are only applying to gain &#39;IRC Operator&#39; status. </li>
        <li>Invalid emails on application form; <br />
          This wastes our time. AustNet <em>will not</em> chase after the applicant. Instead, the application will be immediately rejected. </li>
      </ol>
      <p><strong>Rights during the application process </strong></p>
      <ol>
        <li>AustNet reserves the right to completely discard any complaints or comments which it feels are unjustified or blantant obstructions to the continuation of the application or AustNet. </li>
        <li>AustNet&#39;s decision of the server application administrator is final and futher correspondance with the applicant may be halted. </li>
        <li>AustNet reserves the right to refuse any application for any reason they see fit, without need for explaination or enquiry. </li>
        <li>AustNet may request access to the applying server to confirm aspects of the application or to help assess suitability for a particular region. The applicant has the right to reject this (even though it may hinder the application), or request it be done with supervision of some form. </li>
      </ol>
      <p><strong>AustNet server application procedure:</strong> </p>
      <p>At any point in the following process the application may be terminated by AustNet with or without explanation. </p>
      <ol>
        <li>Applications will be automatically acknowledged and a receipt sent to the applicant, machine owner (including root@server), as notification that AustNet has recieved their server application and it is pending processing. If any of the emails are invalid (except, of course, root@server), the application will be automatically rejected. It is therefore critical that all fields in the application form precisely and correctly </li>
        <li>NOC, Net-block, network, service provider administration will be contacted by the appropriate zone representative to confirm permission. They will be informed of the bandwidth usage by the server, and the potential for malicious attacks. </li>
        <li>The application will sit for <strong>at least</strong> 3 (three) days to allow for comments from the public. It will then be verified and thoroughly assessed by the zone representative for accuracy and honesty. Any falsifications will result in immediate rejection. </li>
        <li>Assuming the server meets requirements, the application will then be forwarded to the entire routing committee for a vote. A majority must agree to a testlink. If the vote ends inconclusively (for example, a tied vote), the application <em>will not</em> be test-linked. </li>
        <li>In the event of a test-link, the applicant will be notified, as will AustNet administration via <a href="mailto:&#097;&#100;&#109;&#105;&#110;&#064;&#097;&#117;&#115;&#116;&#110;&#101;&#116;&#046;&#111;&#114;&#103;">&#097;&#100;&#109;&#105;&#110;&#064;&#097;&#117;&#115;&#116;&#110;&#101;&#116;&#046;&#111;&#114;&#103;</a>. If the applicant chooses to continue with a test-link, the appropriate arrangements will be made (for example server configuration, latest software, et cetera). </li>
        <li>The server will be test-linked for <strong>minimum</strong> of 30 days, during which complaints and objections will be accepted and the status of the application considered by the network as a whole, decided by a vote open to all on the AustNet vote roll at the end of the test-link period. This time should be used by both the applicant, the server sponsor (if any) and the appropriate AustNet Administration to further assess the appropriateness and suitability of the server on the network. </li>
      </ol>
      <p>Note that the The total application process may take up to 2 (two) months or longer before a server is accepted as an official AustNet server. </p>
      <p>Application statistics show that only around <strong>3%</strong> of all applications are granted a permanent link to AustNet.</p>      </div>
    </div>
    <div id="news">
<a href="http://www.austnet.org/news.php?action=fullnews&id=2">New US Server, shadow.*</a>, by Trip posted on 06 April, 2006<br />
<br /><a href="http://www.austnet.org/news.php?action=fullnews&id=1">The new AustNet.org web site is here</a>, by Austnet posted on 14 September, 2005<br />
<br />    </div>
    <div id="navMenu">
      <div id="navMenu2">
        <div id="lselect">
          <ul>
            <li><a href="index.php" title="Home" accesskey="a">Home</a></li>
            <li><a href="about_us.php" title="About Us" accesskey="b">About Us</a></li>
            <li><a href="contact_us.php" title="Contact Us" accesskey="c">Contact Us</a></li>
            <li><a href="servers.php" title="Servers" accesskey="d">Servers</a></li>
            <li><a href="austnet_board.php" title="Administration" accesskey="e">Administration</a></li>
            <li><a href="routing.php" title="Routing" accesskey="f">Routing</a></li>
            <li><a href="services.php" title="Services" accesskey="g">Services</a></li>
            <li><a href="#" title="Support" accesskey="h">Support</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="footer">
    <a href="index.php" title="Home">Home</a> &nbsp;&nbsp;
    <a href="user_agreement.php" title="User Agreement">User Agreement</a> &nbsp;&nbsp;
    <a href="privacy.php" title="Privacy">Privacy</a> &nbsp;&nbsp;
    <a href="about_us.php" title="About Us">About Us</a> &nbsp;&nbsp;
    <a href="contact_us.php" title="Contact Us">Contact Us</a> 
  </div>
  <div id="copyright">
    <span>Copyright &copy; 2006 AustNet. All rights reserved.</span>
  </div>  
  <div id="fixDiv1"><span></span></div>
  <div id="fixDiv2"><span></span></div>
  <div id="fixDiv3"><span></span></div>
</body>
</html>
